# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel McBrayer
email: dmcbrayer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Daniel McBrayer, web aficionado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmcbrayer.github.io" # the base hostname & protocol for your site
facebook_username: daniel.mcbrayer.10
instagram_username: dmcbrayer
twitter_username: dmcbrayer
github_username:  dmcbrayer

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap

# Includes
include: ["_pages"]

# Excludes
exclude: [
  "README.md",
  "gulpfile.js",
  "package.json",
  "node_modules",
  "bower.json",
  "bower_components",
  "_assets"
]
